# Generated by Django 5.1.6 on 2025-02-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
