# Generated by Django 5.1.6 on 2025-02-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_is_authenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='is_authenticated',
        ),
        migrations.AddField(
            model_name='author',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
